apiVersion: v1
kind: Service
metadata:
  name: converter
spec:
  selector:
    app: converter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
      - name: converter
        image: converter:latest
        ports:
        - containerPort: 5003
